### ISSUE TITLE
Feature request: new SeqLib category 

### ISSUE THREAD

**Issue by jsonbl** [cjfuller/labdb#109]
C, Next time you update labdb, can you add a new category so we can keep track of genome sequencing libraries. It would be great if they have the following fields.  I realize we could use the Sample category, but we're generating enough of these libraries that it would be helpful to keep them all in one location with a dedicated database category. Thanks! -J

Genome:
Method (RNA-seq, ATAC-seq, HiC, ChAR-seq, etc):
Made by:
Project:
Storage Location:

Concentration:
Size distribution:
Index ID:
Index Seq:

Description:

Linked Items (Bioanalyzer trace, QC docs, raw and processed data):

**Comment by cjfuller** [comment]
Ok @jsonbl, it should be live now! Holler if anything seems amiss.

**Comment by jsonbl** [comment]
Thanks @cjfuller! This is a great new feature!
