### ISSUE TITLE
Can't edit inventory location information

### ISSUE THREAD

**Issue by whijo2** [cjfuller/labdb#88]
#When I go to edit an entry, I'm unable to edit the location, stock counts, person, or date fields under inventory. Help me, Colin Fuller... you're my only hope!

**Comment by cjfuller** [comment]
I realize now that there's no way to add a new row, which is definitely a bug!  Are you also unable to edit existing inventory information?  I'm able to do that.

**Comment by whijo2** [comment]
Ahhh I see... yes, I can edit existing info in those fields, but I was looking at an entry where I hadn't put any info there yet... so it wasn't letting me edit at all.

**Comment by cjfuller** [comment]
There's now a button to add a row when you're editing the TC line!
