### ISSUE TITLE
Duplicate/delete database entries

### ISSUE THREAD

**Issue by btf6** [cjfuller/labdb#92]
I accidentally created a database entry when trying to figure out if duplication were possible...  Now I can't delete it....

**Comment by cjfuller** [comment]
(Also in the hamburger menu when you're on the item's page.)

**Comment by btf6** [comment]
So apparently the delete feature is only conferred by being an admin -- is
it possible to make this a general ability people with "write" access can
do?

**Comment by cjfuller** [comment]
Oops, yep, I set the button to show for people with "edit" access, which doesn't exist.  Will deploy an updated version shortly.

**Comment by cjfuller** [comment]
Ok, the fix is live, and the button should show up after a refresh of the page.

It should be safe to restore everyone's permissions now.
