### ISSUE TITLE
Can't open plasmid entries

### ISSUE THREAD

**Issue by yycao** [cjfuller/labdb#96]
I did not see a create ASBS link so I wrote in the ASBS # that would have come next and tried to save. This caused a delete symbol to appear and the site stopped functioning. I refreshed and now I cannot open any plasmid entries either from firefox (closed and opened), nor using Chrome. Sorry I broke it...

Update. This returned to normal after I made an ASBS entry.

**Comment by cjfuller** [comment]
Ok, I will look at this this weekend; I'm probably assuming somewhere that every item that is mentioned exists, which is a bad assumption.  Thanks for reporting it!

**Comment by cjfuller** [comment]
Fixed by a5889a14b92000acf10d4c6cdf895adb44a9f9c4
