### ISSUE TITLE
Error when trying to navigate between entries

### ISSUE THREAD

**Issue by whijo2** [cjfuller/labdb#98]
This may be a recent error... but when I'm viewing a specific entry and then try to navigate to the entry before or after with the arrow buttons at the top, I get "We're sorry, but something went wrong".

**Comment by cjfuller** [comment]
Probably new!  Is there a specific entry you're seeing this on?  I tested this yesterday, so I think it is working for at least some entries, and having examples would help to narrow it down.  Thanks!

**Comment by whijo2** [comment]
It's not working for Bradley either, on any of the entries we've tried. Example: ASON 4067. We agree that this seems to have started happening very recently?

**Comment by cjfuller** [comment]
Eep, sorry, I realized I deployed two new versions recently and it was of course only working on the one on which I tested this.

Fix should be live now!
